const WEBSITE_BASE_URL = 'https://www.navplan.ch/v2/';

export const environment = {
    production: true,
    mapOversizeFactor: 1.3,
    iconBaseUrl: './assets/icon/',
    aircraftApiBaseUrl: WEBSITE_BASE_URL + 'api/aircrafts',
    aircraftTypeDesignatorApiBaseUrl: WEBSITE_BASE_URL + 'api/aircrafts/typedesignators',
    airportApiBaseUrl: WEBSITE_BASE_URL + 'api/aerodromes',
    airportChartApiBaseUrl: WEBSITE_BASE_URL + 'api/aerodromes/charts',
    airportCircuitApiBaseUrl: WEBSITE_BASE_URL + 'api/aerodromes/circuits',
    airportReportingPointApiBaseUrl: WEBSITE_BASE_URL + 'api/aerodromes/reportingpoints',
    airspaceApiBaseUrl: WEBSITE_BASE_URL + 'api/airspaces',
    navaidApiBaseUrl: WEBSITE_BASE_URL + 'api/navaids',
    exporterBaseUrl: WEBSITE_BASE_URL + 'api/exports',
    exportBaseUrl: WEBSITE_BASE_URL + 'tmp/',
    flightrouteApiBaseUrl: WEBSITE_BASE_URL + 'api/flightroutes',
    metarTafBaseUrl: WEBSITE_BASE_URL + 'api/metartaf',
    meteoForecastApiBaseUrl: WEBSITE_BASE_URL + 'api/meteo/forecasts',
    meteoForecastMapTilesUrl: WEBSITE_BASE_URL + 'meteo_forecast/',
    meteogramApiBaseUrl: WEBSITE_BASE_URL + 'api/meteograms',
    meteoSmaApiBaseUrl: WEBSITE_BASE_URL + 'api/meteo/measurements',
    notamRestApiBaseUrl: WEBSITE_BASE_URL + 'api/notams',
    searchTextApiBaseUrl: WEBSITE_BASE_URL + 'api/search/text',
    searchPositionApiBaseUrl: WEBSITE_BASE_URL + 'api/search/position',
    trackApiBaseUrl: WEBSITE_BASE_URL + 'api/tracks',
    trafficAdsbexApiBaseUrl: WEBSITE_BASE_URL + 'api/traffic/adsbex',
    trafficOgnApiBaseUrl: WEBSITE_BASE_URL + 'api/traffic/ogn',
    trafficDetailApiBaseUrl: WEBSITE_BASE_URL + 'api/traffic/details',
    userApiBaseUrl: WEBSITE_BASE_URL + 'api/user',
    verticalMapApiBaseUrl: WEBSITE_BASE_URL + 'api/verticalmap',
    webcamApiBaseUrl: WEBSITE_BASE_URL + 'api/webcams',
    chartBaseUrl: WEBSITE_BASE_URL + 'charts/',
    mapTilesIcaoChartUrl: WEBSITE_BASE_URL + 'maptiles/icao_ch_aero/',
    mapTilesGliderChartUrl: WEBSITE_BASE_URL + 'maptiles/icao_ch_glider/',
};
