<?php


class MySqliMock extends mysqli
{
    public function __construct(string $host, string $username, string $passwd, string $dbname, int $port, string $socket)
    {
        // parent::__construct($host, $username, $passwd, $dbname, $port, $socket);
    }


    public function connect($host, $user, $password, $database, $port, $socket)
    {
        // parent::connect($host, $user, $password, $database, $port, $socket); // TODO: Change the autogenerated stub
    }


    public function query($query, $resultmode = MYSQLI_STORE_RESULT)
    {
        // parent::query($query, $resultmode); // TODO: Change the autogenerated stub
    }
}
